apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eku0xgx4a-nodejs
  janus-idp.io/tekton: eku0xgx4a-nodejs
  backstage.io/kubernetes-id: eku0xgx4a-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eku0xgx4a-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
